set_profile:
  name: Set profile
  description: Set mowing profile (1..3).
  fields:
    profile:
      required: true
      selector:
        number:
          min: 1
          max: 3
          mode: slider
    return_response:
      required: false
      default: true
      selector:
        boolean: {}
    log_response:
      required: false
      default: false
      selector:
        boolean: {}

work_now:
  name: Work now
  description: Start mowing immediately.
  fields:
    return_response:
      default: true
      selector: { boolean: {} }
    log_response:
      default: false
      selector: { boolean: {} }

border_cut:
  name: Border cut
  description: Start border cut mode.
  fields:
    return_response:
      default: true
      selector: { boolean: {} }
    log_response:
      default: false
      selector: { boolean: {} }

charge_now:
  name: Charge now
  description: Send mower to charge immediately.
  fields:
    return_response:
      default: true
      selector: { boolean: {} }
    log_response:
      default: false
      selector: { boolean: {} }

charge_until:
  name: Charge until
  description: Charge until weekday/time.
  fields:
    hours:
      required: true
      selector:
        number: { min: 0, max: 23, mode: slider }
    minutes:
      required: true
      selector:
        number: { min: 0, max: 59, mode: slider }
    weekday:
      required: true
      selector:
        number: { min: 1, max: 7, mode: slider }
    return_response:
      default: true
      selector: { boolean: {} }
    log_response:
      default: false
      selector: { boolean: {} }

trace_position:
  name: Trace position
  description: Ask the mower to produce a fresh position fix.
  fields:
    return_response:
      default: true
      selector: { boolean: {} }
    log_response:
      default: false
      selector: { boolean: {} }

keep_out:
  name: Keep out
  description: Add/adjust a temporary keep-out area.
  fields:
    location:
      required: true
      selector:
        object:
    hours:
      required: false
      selector:
        number: { min: 0, max: 23, mode: slider }
    minutes:
      required: false
      selector:
        number: { min: 0, max: 59, mode: slider }
    index:
      required: false
      selector:
        number: { min: 0, max: 9, mode: slider }
    return_response:
      default: true
      selector: { boolean: {} }
    log_response:
      default: false
      selector: { boolean: {} }

wake_up:
  name: Wake up
  description: Nudge modem/radio to push pending data to cloud (SMS UP).
  fields:
    return_response:
      default: true
      selector: { boolean: {} }
    log_response:
      default: false
      selector: { boolean: {} }

thing_find:
  name: thing.find
  description: Diagnostic fetch of the mower thing (also updates sensors).
  fields:
    return_response:
      default: true
      selector: { boolean: {} }
    log_response:
      default: false
      selector: { boolean: {} }

thing_list:
  name: thing.list
  description: Diagnostic fetch (list) of the mower thing (also updates sensors).
  fields:
    return_response:
      default: true
      selector: { boolean: {} }
    log_response:
      default: false
      selector: { boolean: {} }
